### ISSUE TITLE
ต้องการไม่ให้ Bot ทำงานในขณะที่มีแค่ 1 User เข้ามาอยู่ใน Channel นั้น

### ISSUE THREAD

**Issue by pongmile** [chin8628/please-stand-up#1]
ต้องการไม่ให้ Bot ทำงานในขณะที่มีแค่ 1 User เข้ามาอยู่ใน Channel นั้น เพราะไม่จำเป็นที่จะต้องบอกใคร
เช่น Channel นั้นไม่มีคนอยู่ แล้วพอมีแค่ User เดียวเข้ามา Bot ก็ไม่จำเป็นต้องทำงาน

**Comment by chin8628** [comment]
Solved on 78571bbd50e8b631e6b82b7c34c965f7f4c36261
