### ISSUE TITLE
บอทอ่านชื่อบอทตัวอื่น

### ISSUE THREAD

**Issue by Chiibi** [chin8628/please-stand-up#4]
ตอนนี้ condition skip เช็คจาก  `BOT_ID` ของ please stand up เอง ในกรณีที่มีบอทตัวอื่น join channel มาด้วยทำให้มันอ่านชื่อไปด้วย 
น่าจะต้องเปลี่ยนไปเช็คจาก `member.user.bot` แทนว่าถ้าเป็น bot ให้ skip

**Comment by Chiibi** [comment]
https://discord.js.org/#/docs/discord.js/14.7.1/class/User?scrollTo=bot

**Comment by chin8628** [comment]
ถ้างั้นเวลาเล่นเกมแล้วบอทเข้ามา มันก็ไม่รู้ป่ะว่า บอทหรือคน ก็คิดว่าบอทเราพัง
