### ISSUE TITLE
Bot ประกาศชื่อไม่ถูกต้องตอน user เข้าพร้อมกัน

### ISSUE THREAD

**Issue by Chiibi** [chin8628/please-stand-up#5]
กรณีที่ user เข้า/ออก ห้องพร้อมกัน 2 คนขึ้นไป ปกติควรจะประกาศว่า `มี n คนเข้ามาจ้า` แต่ตอนนี้บอทประกาศแค่ `มีสอง... ` แล้วตัดไปอ่านชื่อคนล่าสุดแทน และบางครั้งก็ไม่ประกาศอะไรเลย

**Comment by chin8628** [comment]
fixed on a50a1314a0f3a2991cf1143fc45e7637db57560e
